Repository Trinity-goorm/TRI-FE, pull requests merged in 2025-02, with the labels that each got.

#7 TRI-25 feat:초기세팅
  .gitignore
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/index.css
  src/main.jsx
  vite.config.js
Labels: feat

#14 TRI-33 feat: 카카오 로그인 구현 및 온보딩
  eslint.config.js
  package-lock.json
  package.json
  public/kakaoIcon.png
  public/vite.svg
  src/App.jsx
  src/assets/react.svg
  src/components/SocialKakao.jsx
  src/components/SocialKakaoButton.jsx
  src/components/onbording/OnboardingButton.jsx
  src/components/onbording/OnboardingCategory.jsx
  src/components/onbording/OnboardingPrefPrice.jsx
  src/components/onbording/OnboardingUserInfo.jsx
  src/components/style/BottomBar.js
  src/pages/Login/Login.jsx
  src/pages/login/KakaoCallback.jsx
  src/pages/login/KakaoLogin.jsx
  src/pages/onboarding/Onboarding.jsx
Labels: feat

#20 TRI-34:메인페이지 구현 완료
  package-lock.json
  package.json
  src/App.jsx
  src/assets/dummydata/DetailRestaurant.js
  src/assets/dummydata/RecommendedList.js
  src/assets/dummydata/ReservationResponse.js
  src/components/ConvenienceIcon.jsx
  src/components/banner/Banner.jsx
  src/components/banner/style/Banner.js
  src/components/bar/BottomBar.jsx
  src/components/bar/DetailBottomBar.jsx
  src/components/bar/DetailTopBar.jsx
  src/components/bar/TopBar.jsx
  src/components/bar/style/BottomBar.js
  src/components/bar/style/DetailBottomBar.js
  src/components/bar/style/DetailTopBar.js
  src/components/bar/style/TopBar.js
  src/components/button/ReservationButton.jsx
  src/components/button/style/ReservationButton.js
  src/components/calendar/CustomCalendar.jsx
  src/components/calendar/style/CustomCalendar.css
  src/components/category/CategoryButton.jsx
  src/components/category/CategoryComponent.jsx
  src/components/category/style/CategoryButton.js
  src/components/category/style/CategoryComponent.js
  src/components/map/KakaoMap.jsx
  src/components/menu/MenuComponent.jsx
  src/components/menu/style/MenuComponent.js
  src/components/recommend/RecommendFeed.jsx
  src/components/recommend/style/RecommendFeed.js
  src/components/save/SaveButton.jsx
  src/components/save/style/SaveButton.js
  src/pages/detail/DetailPage.DetailInfo.jsx
  src/pages/detail/DetailPage.Location.jsx
  src/pages/detail/DetailPage.main.jsx
  src/pages/detail/style/DetailPage.DetailInfo.js
  src/pages/detail/style/DetailPage.Location.js
  src/pages/detail/style/DetailPage.main.js
  src/pages/home/HomePage.main.jsx
  src/pages/home/RecommendComponet.main.jsx
  src/pages/reservation/Reservation.modal.confirm.jsx
  src/pages/reservation/Reservation.modal.jsx
  src/pages/reservation/Reservation.table.jsx
  src/pages/reservation/style/Reservation.modal.confirm.js
  src/pages/reservation/style/Reservation.modal.js
  src/pages/reservation/style/Reservation.table.js
Labels: feat

#23 TRI-62 feat: 예약 화면 및 예약 확인 화면 구현
  src/App.jsx
  src/assets/dummydata/ReservationResponse.js
  src/components/button/style/ReservationButton.js
  src/pages/reservation/Reservation.modal.confirm.jsx
  src/pages/reservation/Reservation.modal.jsx
  src/pages/reservation/Reservation.table.jsx
Labels: feat

#37 병합 충돌 및 api 연결
  .dockerignore
  Dockerfile
  src/App.jsx
  src/api/vacancy/delete/DeleteVacancySeat.js
  src/api/vacancy/get/GetVacancySeats.js
  src/api/vacancy/post/PostVacancySeat.js
  src/assets/dummydata/Category.js
  src/assets/dummydata/MyReservation.js
  src/assets/dummydata/RecommendedList.js
  src/assets/img/chicken.html
  src/assets/img/chicken.jpg
  src/assets/img/wine1.jpg
  src/assets/img/winebar.html
  src/components/bar/DetailBottomBar.jsx
  src/components/bar/DetailTopBar.jsx
  src/components/calendar/CustomCalendar.jsx
  src/components/category/style/CategoryButton.js
  src/components/dining/DiningComponent.jsx
  src/components/dining/style/DiningComponent.js
  src/components/icon/CautionIcon.jsx
  src/components/icon/ConvenienceIcon.jsx
  src/components/map/KakaoMap.jsx
  src/components/modal/Modal.jsx
  src/components/modal/style/Modal.js
  src/components/recommend/style/RecommendFeed.js
  src/components/search/SearchReservationItem.jsx
  src/components/search/SearchReservationList.jsx
  src/pages/detail/DetailPage.DetailInfo.jsx
  src/pages/detail/DetailPage.main.jsx
  src/pages/detail/style/DetailPage.main.js
  src/pages/mydining/MyDiningPage.main.jsx
  src/pages/mydining/MyDiningPage.reservation.jsx
  src/pages/mydining/MyDiningPage.vacancy.jsx
  src/pages/mydining/style/MyDiningPage.main.js
  src/pages/mydining/style/MyDiningPage.sub.js
  src/pages/reservation/Reservation.modal.confirm.jsx
  src/pages/reservation/Reservation.modal.jsx
  src/pages/reservation/Reservation.table.jsx
  vite.config.js
Labels: feat

#44 hotfix: Update Reservation.modal.confirm.jsx
  src/pages/reservation/Reservation.modal.confirm.jsx
Labels: release

#46 TRI-129 feat:배포 오류 수정
  src/pages/mydining/MyDiningPage.reservation.jsx
  src/pages/reservation/Reservation.modal.confirm.jsx
  src/pages/reservation/Reservation.table.jsx
Labels: feat

#50 환경변수 관련 수정
  .gitignore
  index.html
  public/firebase-messaging-sw.js
  src/components/modal/style/Modal.js
  src/pages/mydining/MyDiningPage.reservation.jsx
  src/pages/mydining/MyDiningPage.vacancy.jsx
Labels: release

#53 환경변수 관련 수정사안
  public/firebase-messaging-sw.js
  src/pages/mydining/MyDiningPage.vacancy.jsx
Labels: release

#58 로그인 확인
  public/firebase-messaging-sw.js
  src/api/auth/PostLogin.js
  src/components/auth/SocialKakaoButton.jsx
  src/components/bar/TopBar.jsx
  src/pages/auth/KakaoCallback.jsx
Labels: fix

#64 TRI-149 fix: 환경변수 수정
  public/firebase-messaging-sw.js
Labels: fix
